name: ci-pipeline
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for SonarCloud to analyze git history

      - name: Generate RSA keys if missing
        run: |
          if [ ! -f "./private.pem" ] || [ ! -f "./public.pem" ]; then
            make generate-rsa-key
          fi

      - name: Check lint
        if: ${{ github.event_name == 'pull_request' }}
        run: make docker-lint

      - name: Run test
        run: make docker-test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.exclusions=**/*_test.go,**/test/**/*,**/mocks/**/*,**/fixture/**/*
            -Dsonar.cpd.exclusions=**/*_test.go,**/test/**/*,**/mocks/**/*,**/fixture/**/*
            -Dsonar.coverage.exclusions=**/*_test.go,**/test/**/*,**/mocks/**/*,**/fixture/**/*

      - name: Login to Docker Hub
        if: ${{ github.event_name != 'pull_request' }}
        run: make docker-login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        if: ${{ github.event_name != 'pull_request' }}
        run: make docker-release